crop_thresh: 0.5
kpt_thresh: 0.2
visual: True
warmup_frame: 50

MOT:
#  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_pipeline.zip
#  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_s_36e_pipeline.zip
  #  model_dir: output_inference/mot_ppyoloe_l_36e_pipeline
  model_dir: output_inference/ppyoloe_plus_crn_t_auxhead_320_60e_pphuman
#  model_dir: output_inference/mot_ppyoloe_s_36e_pipeline
  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  skip_frame_num: 3 # preferably no more than 3
  enable: False

KPT:
#  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip
  model_dir: output_inference/dark_hrnet_w32_256x192
  batch_size: 1
  enable: False

SKELETON_ACTION:
#  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/STGCN.zip
  model_dir: output_inference/STGCN
  batch_size: 1
  max_frames: 50
  display_frames: 80
  coord_size: [384, 512]
  enable: True
